/**
 * ============================================================
 * LeetCode 389: Find the Difference
 * ============================================================
 *
 * Problem Statement:
 *   Given two strings s and t:
 *
 *   - t is generated by shuffling s
 *   - one extra letter is added
 *
 *   Return the extra letter.
 *
 * Examples:
 *   s = "abcd", t = "abcde" → 'e'
 *   s = "", t = "y"         → 'y'
 *
 * Constraints:
 *   - 0 <= s.length <= 1000
 *   - t.length == s.length + 1
 *   - lowercase English letters
 */

#include <unordered_map>
#include <string>
using namespace std;

class Solution {
public:
    /**
     * ============================================================
     * Main Function: findTheDifference
     * ============================================================
     *
     * Approach (Frequency Difference Counting):
     *
     *   1. Count frequency of characters in s
     *   2. Subtract frequency using characters in t
     *   3. The character with negative balance is the extra one
     *
     * Time Complexity:  O(n)
     *   - Single pass counting + scan
     *
     * Space Complexity: O(1)
     *   - Fixed alphabet size
     */
    char findTheDifference(string s, string t) {
        unordered_map<char, int> freq;

        for (const char& c : s) {
            freq[c]++;
        }

        for (const char& c : t) {
            freq[c]--;
        }

        for (const auto& entry : freq) {
            if (entry.second < 0) {
                return entry.first;
            }
        }

        return 'a'; // fallback (problem guarantees answer exists)
    }
};

/*
 * ============================================================
 * Study Notes & Key Takeaways
 * ============================================================
 *
 * DSA Pattern:
 *   - Frequency difference tracking
 *   - Counting imbalance detection
 *
 * Core Insight:
 *   Matching characters cancel out.
 *   The leftover imbalance reveals the extra character.
 *
 * Mental Model:
 *   "Add counts → subtract counts → leftover is answer."
 *
 * ============================================================
 * Edge Cases
 * ============================================================
 *
 * - s empty → extra char is first char of t
 * - repeated characters
 * - shuffled input order
 *
 * ============================================================
 * Interview Explanation (Concise)
 * ============================================================
 *
 * "We track frequency differences between the two strings.
 *  The character with leftover count is the extra one."
 *
 * ============================================================
 * Common Mistakes
 * ============================================================
 *
 * - Forgetting repeated characters
 * - Early exit before full balancing
 * - Using sorting unnecessarily (O(n log n))
 *
 * ============================================================
 * Optimization Insight
 * ============================================================
 *
 * Faster alternatives:
 *
 * 1. XOR trick (constant memory):
 *
 *      char ans = 0;
 *      for (char c : s + t) ans ^= c;
 *
 * 2. Fixed array counting:
 *
 *      int freq[26] = {};
 *
 * ============================================================
 * Related Problems
 * ============================================================
 *
 * - 383. Ransom Note
 * - 242. Valid Anagram
 * - 136. Single Number
 */
